version: '3'

services:
  app:
    build: .
    volumes:
      - .:/data

  web:
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app
